NullabilityTests.swift, unannotatedReturn_bad, 1, MISSING_NULLABILITY_ANNOTATION, no_bucket, ERROR, []
NullabilityTests.swift, macroAnnotatedUnannotatedProp_bad, 1, MISSING_NULLABILITY_ANNOTATION, no_bucket, ERROR, []
NullabilityTests.swift, swiftRefinedNullableString_good_FP, 1, MISSING_NULLABILITY_ANNOTATION, no_bucket, ERROR, []
NullabilityTests.swift, unannotatedReturn_castAsOptional_good_FP, 1, MISSING_NULLABILITY_ANNOTATION, no_bucket, ERROR, []
