name: docker-java

on:
  - push
  - pull_request

jobs:
  java:
    name: Java Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Required Apt Packages
        run: |
            sudo apt install opam
            sudo apt clean

      - name: Build Infer for Java
        run: ./build-infer.sh --yes java

      - name: Run Direct Java Tests
        run: make direct_java_racerd_test direct_java_pulse_test direct_java_nullsafe_test

      - name: Run Maven Integration Tests
        run: make build_mvn_test

  erlang:
    name: Erlang Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Required Apt Packages
        run: |
            sudo apt install opam
            sudo apt clean

      - name: Build Infer for Erlang
        run: ./build-infer.sh --yes erlang
